In [2]:
import numpy as np
import pandas as pd
import plotly
import plotly.express as px
plotly.offline.init_notebook_mode (connected = True)

In [3]:
df = pd.read_csv("C://Users//91944//OneDrive//Documents//GitHub//Maths-Project-LDA//test-data-revised.csv") # Iris dataset


In [4]:
df.head()

A        B         C STATUS
0  0.65625  0.00000  0.000000     NO
1  0.62500  0.03125  0.019531    YES
2  0.59375  0.06250  0.035156    YES
3  0.56250  0.09375  0.052734     NO
4  0.53125  0.12500  0.054688    YES

In [5]:
df.corr().style.background_gradient(cmap='coolwarm') # Correlation between features as a heatmap

In [71]:
feats = df.columns[:-1]
feats

Index(['A', 'B', 'C'], dtype='object')

CHECKING THE RANGE OF EACH FEATURE

In [50]:
fig = px.bar(df[feats].min(), title='Features Min Values')
fig.layout.xaxis.tickangle = 300
fig.update_traces(showlegend = True)
fig.layout.xaxis. dtick = 1
fig.layout.xaxis.title = ''
fig.layout.yaxis.title = ''
fig.show()

In [49]:
fig = px.bar(df[feats].max(), title='Features Max Values')
fig.layout.xaxis.tickangle = 300
fig.update_traces(showlegend = True)
fig.layout.xaxis. dtick = 1
fig.layout.xaxis.title = ''
fig.layout.yaxis.title = ''
fig.show()

SCALING THE FEATURES USING STANDARDIZATION

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit_transform(df[feats])

In [13]:
scaled = pd.DataFrame(scaler, columns=feats)
scaled['STATUS'] = df['STATUS']


scaled

A        B         C STATUS
0   2.04939 -2.04939 -1.265772     NO
1   1.85421 -1.85421 -0.663024    YES
2   1.65903 -1.65903 -0.180825    YES
3   1.46385 -1.46385  0.361649     NO
4   1.26867 -1.26867  0.421924    YES
..      ...      ...       ...    ...
59 -1.26867  1.26867 -0.904123    YES
60 -1.46385  1.46385 -1.265772     NO
61 -1.65903  1.65903 -1.205498    YES
62 -1.85421  1.85421 -1.265772    YES
63 -2.04939  2.04939 -1.265772     NO

[64 rows x 4 columns]

AFTER SCALING

In [51]:
fig = px.bar(scaled[feats].min(), title='Features Min Values')
fig.layout.xaxis.tickangle = 300
fig.update_traces(showlegend = False)
fig.layout.xaxis. dtick = 1
fig.layout.xaxis.title = ''
fig.layout.yaxis.title = ''
fig.show()

In [48]:
fig = px.bar(scaled[feats].max(), title='Features Max Values')
fig.layout.xaxis.tickangle = 300
fig.update_traces(showlegend = False)
fig.layout.xaxis. dtick = 1
fig.layout.xaxis.title = ''
fig.layout.yaxis.title = ''
fig.show()

BEFORE PCA

In [18]:
fig = px.scatter_3d(scaled, x='A', y='B', z='C',
              color='STATUS', symbol='STATUS')
fig.update_layout(width=800, height=800)
fig.update_traces(marker=dict(size=2.5))
fig.show()

In [19]:
df.head()

A        B         C STATUS
0  0.65625  0.00000  0.000000     NO
1  0.62500  0.03125  0.019531    YES
2  0.59375  0.06250  0.035156    YES
3  0.56250  0.09375  0.052734     NO
4  0.53125  0.12500  0.054688    YES

In [20]:
X, y = df.drop(['STATUS'], axis=1), df['STATUS']

In [21]:
from sklearn.decomposition import PCA

In [22]:
# Function to create pca with 'n' components
def create_pca(X, y, n_components=None):
    if (n_components != None):
        pca = PCA(n_components)
    else:
        pca = PCA()
    trans = pca.fit_transform(X)
    trans = pd.DataFrame(trans)
    trans['species'] = y
    return pca, trans

AFTER PCA

In [23]:
pca1, trans1 = create_pca(X=X, y=y, n_components=3)
pca2, trans2 = create_pca(X=X, y=y, n_components=2)
pca3, trans3 = create_pca(X=X, y=y, n_components=1)

In [24]:
pca1.explained_variance_ratio_

array([9.83441739e-01, 1.65582610e-02, 1.43020697e-32])

In [25]:
# Eigenvectors for the 3 variables
pca1.components_

array([[-7.05821903e-01,  7.05821903e-01, -6.02568057e-02],
       [ 4.26079959e-02, -4.26079959e-02, -9.98182908e-01],
       [-7.07106781e-01, -7.07106781e-01,  2.77966702e-16]])

In [28]:
fig = px.scatter_3d(trans1, x=0, y=1, z=2, color='species', symbol='species')
fig.update_layout(width=800, height=800)
fig.update_traces(marker=dict(size=2.5))
fig.show()

n components = 2

In [29]:
pca2.explained_variance_ratio_

array([0.98344174, 0.01655826])

In [30]:
# Eigenvectors for the s variables
pca2.components_

array([[-0.7058219 ,  0.7058219 , -0.06025681],
       [ 0.042608  , -0.042608  , -0.99818291]])

In [31]:
fig = px.scatter(trans2, x=0, y=1, color='species', symbol='species')
fig.update_traces(marker=dict(size=5))
fig.show()

n omponents =1

In [32]:
pca3.explained_variance_ratio_

array([0.98344174])

In [33]:
# Eigenvectors for the 1 variable
pca3.components_

array([[-0.7058219 ,  0.7058219 , -0.06025681]])

In [34]:
trans3[1] = np.zeros_like(trans3[0]) + 1
fig = px.scatter(trans3, x=0, y=1, color='species', symbol='species')
fig.update_traces(marker=dict(size=5))
fig.show()