In [2]:
import numpy as np
import pandas as pd
import plotly
import plotly.express as px
plotly.offline.init_notebook_mode (connected = True)
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("C://Users//91944//OneDrive//Documents//GitHub//Maths-Project-LDA//test-data-revised.csv") # Iris dataset


In [4]:
df.corr().style.background_gradient(cmap='coolwarm') # Correlation between features as a heatmap

In [5]:
feats = df.columns[:-1]
feats

Index(['A', 'B', 'C'], dtype='object')

In [6]:
fig = px.bar(df[feats].min(), title='Features Min Values')
fig.layout.xaxis.tickangle = 300
fig.update_traces(showlegend = True)
fig.layout.xaxis. dtick = 1
fig.layout.xaxis.title = ''
fig.layout.yaxis.title = ''
fig.show()

In [7]:
fig = px.bar(df[feats].max(), title='Features Max Values')
fig.layout.xaxis.tickangle = 300
fig.update_traces(showlegend = True)
fig.layout.xaxis. dtick = 1
fig.layout.xaxis.title = ''
fig.layout.yaxis.title = ''
fig.show()

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit_transform(df[feats])

In [9]:
scaled = pd.DataFrame(scaler, columns=feats)
scaled['STATUS'] = df['STATUS']


scaled

A        B         C STATUS
0   2.04939 -2.04939 -1.265772     NO
1   1.85421 -1.85421 -0.663024    YES
2   1.65903 -1.65903 -0.180825    YES
3   1.46385 -1.46385  0.361649     NO
4   1.26867 -1.26867  0.421924    YES
..      ...      ...       ...    ...
59 -1.26867  1.26867 -0.904123    YES
60 -1.46385  1.46385 -1.265772     NO
61 -1.65903  1.65903 -1.205498    YES
62 -1.85421  1.85421 -1.265772    YES
63 -2.04939  2.04939 -1.265772     NO

[64 rows x 4 columns]

In [25]:
fig = px.bar(scaled[feats].min(), title='Features Min Values')
fig.layout.xaxis.tickangle = 300
fig.update_traces(showlegend = False)
fig.layout.xaxis. dtick = 1
fig.layout.xaxis.title = ''
fig.layout.yaxis.title = ''
fig.show()

In [26]:
fig = px.bar(scaled[feats].max(), title='Features Max Values')
fig.layout.xaxis.tickangle = 300
fig.update_traces(showlegend = False)
fig.layout.xaxis. dtick = 1
fig.layout.xaxis.title = ''
fig.layout.yaxis.title = ''
fig.show()

BEFORE PCA

In [12]:
import plotly.express as px

features = ["A", "B", "C"]

fig = px.scatter_matrix(
    scaled,
    dimensions=features,
    color="STATUS"
)
fig.update_traces(diagonal_visible=True)
fig.show()


In [13]:
df.head()

A        B         C STATUS
0  0.65625  0.00000  0.000000     NO
1  0.62500  0.03125  0.019531    YES
2  0.59375  0.06250  0.035156    YES
3  0.56250  0.09375  0.052734     NO
4  0.53125  0.12500  0.054688    YES

In [14]:
X, y = df.drop(['STATUS'], axis=1), df['STATUS']

AFTER PCA

In [15]:
from sklearn.decomposition import PCA

In [16]:
# Function to create pca with 'n' components
def create_pca(X, y, n_components=None):
    if (n_components != None):
        pca = PCA(n_components)
    else:
        pca = PCA()
    trans = pca.fit_transform(X)
    trans = pd.DataFrame(trans)
    trans['species'] = y
    return pca, trans

In [17]:
pca1, trans1 = create_pca(X=X, y=y, n_components=3)
pca2, trans2 = create_pca(X=X, y=y, n_components=2)
pca3, trans3 = create_pca(X=X, y=y, n_components=1)

In [18]:
pca1.explained_variance_ratio_

array([9.83441739e-01, 1.65582610e-02, 1.43020697e-32])

In [19]:
# Eigenvectors for the 3 variables
pca1.components_

array([[-7.05821903e-01,  7.05821903e-01, -6.02568057e-02],
       [ 4.26079959e-02, -4.26079959e-02, -9.98182908e-01],
       [-7.07106781e-01, -7.07106781e-01,  2.77966702e-16]])

In [20]:
pca2.explained_variance_ratio_

array([0.98344174, 0.01655826])

In [21]:
pca2.components_

array([[-0.7058219 ,  0.7058219 , -0.06025681],
       [ 0.042608  , -0.042608  , -0.99818291]])

In [22]:
pca3.explained_variance_ratio_

array([0.98344174])

In [23]:
import plotly.express as px

features = ['A','B','C']

pca = PCA()
components = pca.fit_transform(df[features])
labels = {
    str(i): f"PC {i+1} ({var:.1f}%)"
    for i, var in enumerate(pca.explained_variance_ratio_ * 100)
}
fig = px.scatter_matrix(
components,
labels=labels,
dimensions=range(len(features)),
color=df["STATUS"]
)
fig.update_traces(diagonal_visible=True)
fig.show()
